#!/usr/bin/with-contenv bash

if [ ! -f "/etc/apt/sources.list.d/kubernetes.list" ]; then
    echo "**** Adding kubectl packages to install list ****"
    mkdir -p -m 755 /etc/apt/keyrings
    kubectl_version="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
    kubectl_minor="${kubectl_version%.*}"
    curl -fsSL "https://pkgs.k8s.io/core:/stable:/${kubectl_minor}/deb/Release.key" | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${kubectl_minor}/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
    chmod 644 /etc/apt/sources.list.d/kubernetes.list
    echo "kubectl" >> /mod-repo-packages-to-install.list
else
    echo "**** Kubectl packages already installed, skipping ****"
fi
