#!/usr/bin/with-contenv bash

set -e

if [ -f /usr/bin/apt ]; then
	echo "unzip" >> /mod-repo-packages-to-install.list
fi

if [ -f /sbin/apk ]; then
	echo "unzip" >> /mod-repo-packages-to-install.list
fi